version: '3'
services:
        mongo:
          image: 'mongo:3.4.1'
          ports:
            - '27017:27017'
          volumes:
            - 'mongo:/data/db'
        web:
                depends_on:
                  - 'mongo'
                build:
                  context: .
                  dockerfile: Dockerfile
                ports:
                        - "80:3000"
                env_file:
                        - ./secrets.env
                environment:
                      PORT: 3000
volumes:
  mongo: